// <auto-generated />
namespace ConcessionariaMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _321212124 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_321212124));
        
        string IMigrationMetadata.Id
        {
            get { return "202409030209055_321212124"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
